### ISSUE TITLE
Modelagem do banco de dados de clientes

### ISSUE THREAD

**Issue by camillabarreto** [pji-2/self-service#10]

**Comment by ElisaaRodrigues** [comment]
As informações que serão armazenadas para identificar os clientes serão
- _Nome do cliente_
- _CPF do cliente que será seu identificador_
- _Saldo para compras do cliente_
- _Senha para acesso_

Os clientes irão se relacionar com os produtos a partir das vendas realizadas.

**Segue link do diagrama UML**
[DiagramaUML](https://drive.google.com/file/d/1LlUHm6FdLB9TppLyRP51iHJ15xFBumjU/view?usp=sharing)
