### ISSUE TITLE
Instalar sistema operacional na Raspberry

### ISSUE THREAD

**Issue by camillabarreto** [pji-2/self-service#11]

**Comment by sarom-torres** [comment]
### Sistema operacional instalado no cartão SD da Raspberry Pi

**OS:** _Android Things_
**Android version:** 8.1.0
**Android API Level:** 27
**Android Things version:** 1.0.14
**Android Things API Level:** 1
**Build:** OIM1.180327.092 (userdebug)
**OEM version:** 16
