### ISSUE TITLE
Definir frequência de operação usando tags passivas

### ISSUE THREAD

**Issue by camillabarreto** [pji-2/self-service#12]

**Comment by camillabarreto** [comment]
As tags passivas em geral operam em:
**Baixas frequências (LF):** 125KHz;
**Altas frequências (HF):** 13,56 MHz;
**Ultra alta frequência (UHF):** 860 a 960MHz.

**Comment by ghost** [comment]
Mas qual delas será usada? Será a baixa, conforme #14?

**Comment by camillabarreto** [comment]
Isso está na tarefa da aquisição da Tag, mas posso incluir essa informação
aqui também.

Camilla Barreto de Sousa

Em qui, 19 de set de 2019 08:46, Ederson Torresini <notifications@github.com>
escreveu:

**Comment by ghost** [comment]
Não é necessário. Só fazer a referência a tarefa onde está a informação é suficiente.

**Comment by camillabarreto** [comment]
As tags fornecidas operam na frequência de 125KHz (conforme #14 )
