### ISSUE TITLE
Adquirir o teclado

### ISSUE THREAD

**Issue by camillabarreto** [pji-2/self-service#15]

**Comment by camillabarreto** [comment]
### Especificações:
**Fabricante:** Riitek
**Modelo:**  Mini Wireless Keyboard i8+ With Touchpad Mouse + LED Backlit
**Modo RF:** 2,4 GHz GFSK
**Fonte de alimentação:** bateria recarregável de polímero de lítio-íon de 450mAh
**Tensão de operação:** 3.7V

[Referência](http://www.riitek.com/product/k08x.html)

**Comment by ElisaaRodrigues** [comment]
E o preço?
