### ISSUE TITLE
Adquirir Monitor

### ISSUE THREAD

**Issue by camillabarreto** [pji-2/self-service#16]

**Comment by sarom-torres** [comment]
### Monitor 
**Marca:** BENQ
**Modelo:** ET-0021-B
**Tipo:** LCD
**Entradas:** uma VGA e um de alimentação 
**Alimentação:** 100-240V~, 50-60Hz, (1.0 A) 

### Conector
**Tipo:** VGA - VGA

**Comment by ElisaaRodrigues** [comment]
Trocou o monitor, com suporte a DVI - em uso cabo HDMI-DVI.
