### ISSUE TITLE
Ler sobre RFID

### ISSUE THREAD

**Issue by sarom-torres** [pji-2/self-service#2]

**Comment by camillabarreto** [comment]
### **Tecnologia RFID**
A tecnologia RFID (Radio Frequency Identification) utiliza ondas eletromagnéticas para a identificação de objetos que possuem um cartão ou tag RFID. 

**Sistema RFID**

O sistema é composto basicamente pelo leitor RFID e a tag RFID. 

**Leitor RFID**

O leitor é responsável por induzir energia na tag através de um campo eletromagnético e ler o feedback gerado por ela. O leitor deve estar conectado a um computador para realizar o processamento dos dados de resposta.

**Tag RFID**

As tags são normalmente classificadas como passivas e ativas, onde o que diferencia é a fonte de alimentação. O tipo ativo necessita de um fonte própria de alimentação para enviar dados ao leitor e o tipo passivo vai utilizar a energia enviada pelo leitor para isso.

Outra carcterística que diferencia as tags é a existência de memória para leitura ou leitura/gravação possibilitando o armazenamento de mais informações do que somente a ID.

**Frequências de operação**
- LF (Low Frequency) 125 kHz ou 134 kHz:  alcance de até 10cm.
- HF (High Frequency) 13,56 MHz: alcance de até 1m.
- UHF (Ultra High Frequency) 860 MHz - 960 MHz: alcance de até 10 à 15 m.
