### ISSUE TITLE
Criar banco de dados de produtos

### ISSUE THREAD

**Issue by camillabarreto** [pji-2/self-service#24]

**Comment by ElisaaRodrigues** [comment]
Projeto [Firebase](https://console.firebase.google.com/project/bancodedados-2666c/overview) (acesso restrito ao time de desenvolvimento) criado. Todos os dados serão armazenados neste projeto, no [Firebase Realtime Database](https://console.firebase.google.com/project/bancodedados-2666c/database/bancodedados-2666c/data) (acesso restrito ao time de desenvolvimento) organizados ali, em formas de "diretórios", para que os acessos aos dados sejam mais direcionados.
