### ISSUE TITLE
Reconhecimento de uma TAG

### ISSUE THREAD

**Issue by camillabarreto** [pji-2/self-service#25]

**Comment by camillabarreto** [comment]
**Linguagem:** Python2 

**Código:**
>import serial
ser = serial.Serial('/dev/ttyUSB0', 19200, timeout=5)
x = ser.readline()

**Resultado:** '\x18\x18xx\x00xx`\x80x\x1e\x86x\x80\x9e\x1e\xe6\x80\x98\x80\x1e'

**Comment by ghost** [comment]
Conforme conversado com a @camillabarreto, eu acredito que o uso de codificação UTF-8 ([PEP 263](https://www.python.org/dev/peps/pep-0263/)), com `-*- coding: utf-8 -*-`,  ou mesmo Python3 (onde é padrão), pode ajudar na leitura dos valores.

**Comment by camillabarreto** [comment]
**Modificação:** Velocidade de leitura da porta serial modificado de 19200 para 9600.

**Cartão utilizado no teste:** S:2200D879C7

**Código:**
>import serial
ser = serial.Serial('/dev/ttyUSB0', 9600, timeout=5)
x = ser.readline()
print(x)

**Resultado:** b'\x022200D879C7\r\n'
