### ISSUE TITLE
Documentar requisitos não funcionais do projeto

### ISSUE THREAD

**Issue by camillabarreto** [pji-2/self-service#30]

**Comment by camillabarreto** [comment]
### Requisitos Não Funcionais
- Alimentação dos equipamentos
- Conexão Ethernet
- Leitura de 1 tag por vez
- Monitor (HDMI)
- Teclado (USB)
- Acesso ao banco de dados modelado como previsto (#9, #10)

**(em construção)**

**Comment by ghost** [comment]
A realização de ação mensurável, como ler 1 tag por vez, entendo que é requisito funcional. Não funcional é aquele não tangível ou mensurável, como "sistema deve ter boa usabilidade".

**Comment by camillabarreto** [comment]
### Requisitos Não Funcionais

- Alimentação dos equipamentos
- Conexão Ethernet
- Monitor (HDMI)
- Teclado (USB)
- Acesso ao banco de dados modelado como previsto (#9, #10)

**(em construção)**

**Comment by ghost** [comment]
Acesso ao banco e alimentação também são funcionais. O que vejo sendo não funcional no caso do projeto de vocês:
1. Leitura **rápida** e **efetiva** da *tag*;
1. Apresentação **acessível** dos valores na tela.
1. **Fácil** interface de navegação dos itens para fechar a compra.

**Comment by camillabarreto** [comment]
### Requisitos Não Funcionais

- Apresentar mensagem inicial em tela.
- Possuir interface de navegação intuitiva.
- Realizar leitura fácil e efetiva da tag.
- Apresentar os produtos reconhecidos em tela.
