### ISSUE TITLE
Pesquisa sobre como são criadas classes em python

### ISSUE THREAD

**Issue by ElisaaRodrigues** [pji-2/self-service#33]

**Comment by ElisaaRodrigues** [comment]
Classes são construídas da forma:

`class NomedaClasse:`

onde o nome da classe deve iniciar com letra maiúscula. 
Classes vazias podem ser criadas da forma:

`class NomedaClasse:`
`pass`

Ao criar métodos para a classe pode-se usar o método especial do Python `__init__` onde é um método que sempre é chamado ao instanciar um objeto. No caso, é o método inicializador da classe.
Poderia criar um método do tipo:

`def __init__(self, a, b):`
`self.a = a`
`self.b = b`

Um método clássico de uma classe para obter o valor de algum parâmetro (get) poderia ser definido por:

`def return_a(self)`
`return a`

Todo o método criado dentro de uma classe deve definir primeiro o parâmetro _self_, isso por definição.

**Comment by camillabarreto** [comment]
Para Python 3.
