### ISSUE TITLE
Adicionar banco de dados dos clientes na nuvem

### ISSUE THREAD

**Issue by camillabarreto** [pji-2/self-service#43]

**Comment by ElisaaRodrigues** [comment]
Projeto [Firebase](https://console.firebase.google.com/u/0/project/pji2-ade1a/database/pji2-ade1a/data) criado, com diretório **clients** específico para salvar dados dos clientes. Acesso ao banco de dados restrito ao time de desenvolvimento.

**Comment by camillabarreto** [comment]
Realizado manualmente na interface Web de gerenciamento do serviço.
