### ISSUE TITLE
Pesquisar os tipos de banco de dados e definir um para o projeto.

### ISSUE THREAD

**Issue by sarom-torres** [pji-2/self-service#6]

**Comment by ElisaaRodrigues** [comment]
O modelo de banco de dados escolhido para o projeto foi o relacional, pelo fato de poder relacionar duas tabelas (como são estruturados), no caso a tabela de clientes com a de produtos produtos.
De acordo com o modelo, optamos por usar o SQLite que é uma biblioteca de código aberto para estruturar bancos de dados e se baseia no SQL. Ele é um banco de dados leve e prático, sendo a base de dados mais popular que o Android fornece.
