### ISSUE TITLE
Modelagem do banco de dados de produtos

### ISSUE THREAD

**Issue by camillabarreto** [pji-2/self-service#9]

**Comment by ElisaaRodrigues** [comment]
As informações que serão armazenadas para identificar os produtos serão
- _Nome do produto_
- _Código do produto que será seu identificador_
- _Valor do produto_
- _Quantidade em estoque_

Esses produtos irão se relacionar com os clientes a partir das vendas realizadas.

**Segue link do diagrama UML**
[DiagramaUML](https://drive.google.com/file/d/1LlUHm6FdLB9TppLyRP51iHJ15xFBumjU/view?usp=sharing)
